;;; Compiled snippets and support files for `navigation'
;;; Snippet definitions:
;;;
(yas-define-snippets 'navigation
                     '(("bs3navbar" "\n<nav class=\"navbar navbar-default\" role=\"navigation\">\n	<div class=\"container-fluid\">\n		<!-- Brand and toggle get grouped for better mobile display -->\n		<div class=\"navbar-header\">\n			<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\n				<span class=\"sr-only\">Toggle navigation</span>\n				<span class=\"icon-bar\"></span>\n				<span class=\"icon-bar\"></span>\n				<span class=\"icon-bar\"></span>\n			</button>\n			<a class=\"navbar-brand\" href=\"${1:#}\">${2:Title}</a>\n		</div>\n\n		<!-- Collect the nav links, forms, and other content for toggling -->\n		<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\n			<ul class=\"nav navbar-nav\">\n				<li class=\"active\"><a href=\"#\">Link</a></li>\n				<li><a href=\"#\">Link</a></li>\n			</ul>\n			<form class=\"navbar-form navbar-left\" role=\"search\">\n				<div class=\"form-group\">\n					<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n				</div>\n				<button type=\"submit\" class=\"btn btn-default\">Submit</button>\n			</form>\n			<ul class=\"nav navbar-nav navbar-right\">\n				<li><a href=\"#\">Link</a></li>\n				<li class=\"dropdown\">\n					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a>\n					<ul class=\"dropdown-menu\">\n						<li><a href=\"#\">Action</a></li>\n						<li><a href=\"#\">Another action</a></li>\n						<li><a href=\"#\">Something else here</a></li>\n						<li><a href=\"#\">Separated link</a></li>\n					</ul>\n				</li>\n			</ul>\n		</div><!-- /.navbar-collapse -->\n	</div>\n</nav>\n" "bs3navbar" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar.yasnippet" nil nil)
                       ("bs3navbar:text" "\n<p class=\"navbar-text\">${1:Navbar text}</p>\n" "bs3navbar:text" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-text.yasnippet" nil nil)
                       ("bs3navbar:static-top" "\n<nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\">\n	<div class=\"container\">\n		<a class=\"navbar-brand\" href=\"${1:#}\">${2:Title}</a>\n		<ul class=\"nav navbar-nav\">\n			<li class=\"active\">\n				<a href=\"#\">${3:Home}</a>\n			</li>\n			<li>\n				<a href=\"#\">${4:Link}</a>\n			</li>\n		</ul>\n	</div>\n</nav>\n" "bs3navbar:static-top" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-static-top.yasnippet" nil nil)
                       ("bs3navbar:responsive" "\n<nav class=\"navbar navbar-default\" role=\"navigation\">\n	<div class=\"container-fluid\">\n		<!-- Brand and toggle get grouped for better mobile display -->\n		<div class=\"navbar-header\">\n			<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\n				<span class=\"sr-only\">Toggle navigation</span>\n				<span class=\"icon-bar\"></span>\n				<span class=\"icon-bar\"></span>\n				<span class=\"icon-bar\"></span>\n			</button>\n			<a class=\"navbar-brand\" href=\"${1:#}\">${2:Title}</a>\n		</div>\n\n		<!-- Collect the nav links, forms, and other content for toggling -->\n		<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\n			<ul class=\"nav navbar-nav\">\n				<li class=\"active\"><a href=\"#\">Link</a></li>\n				<li><a href=\"#\">Link</a></li>\n			</ul>\n			<form class=\"navbar-form navbar-left\" role=\"search\">\n				<div class=\"form-group\">\n					<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n				</div>\n				<button type=\"submit\" class=\"btn btn-default\">Submit</button>\n			</form>\n			<ul class=\"nav navbar-nav navbar-right\">\n				<li><a href=\"#\">Link</a></li>\n				<li class=\"dropdown\">\n					<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a>\n					<ul class=\"dropdown-menu\">\n						<li><a href=\"#\">Action</a></li>\n						<li><a href=\"#\">Another action</a></li>\n						<li><a href=\"#\">Something else here</a></li>\n						<li><a href=\"#\">Separated link</a></li>\n					</ul>\n				</li>\n			</ul>\n		</div><!-- /.navbar-collapse -->\n	</div>\n</nav>\n" "bs3navbar:responsive" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-responsive.yasnippet" nil nil)
                       ("bs3navbar:links" "\n<ul class=\"nav navbar-nav\">\n	<li class=\"active\">\n		<a href=\"${1:#}\">${2:Home}</a>\n	</li>\n	<li>\n		<a href=\"${3:#}\">${4:Link}</a>\n	</li>\n</ul>\n" "bs3navbar:links" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-links.yasnippet" nil nil)
                       ("bs3navbar:link" "\n<p class=\"navbar-text pull-${1:right}\">\n	<a href=\"${2:#}\" class=\"navbar-link\">${3:Links}</a>\n</p>\n" "bs3navbar:link" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-link.yasnippet" nil nil)
                       ("bs3navbar:inverse" "\n<nav class=\"navbar navbar-inverse\">\n	<div class=\"container-fluid\">\n		<a class=\"navbar-brand\" href=\"#\">${1:Title}</a>\n		<ul class=\"nav navbar-nav\">\n			<li class=\"active\">\n				<a href=\"#\">${2:Home}</a>\n			</li>\n			<li>\n				<a href=\"#\">${3:Link}</a>\n			</li>\n		</ul>\n	</div>\n</nav>\n" "bs3navbar:inverse" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-inverse.yasnippet" nil nil)
                       ("bs3navbar:form" "\n<form class=\"navbar-form pull-${1:right}\">\n	<input type=\"text\" style=\"width: 200px;\">\n	<button type=\"submit\" class=\"btn btn-${2:default}\">${3:Submit}</button>\n</form>\n" "bs3navbar:form" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-form.yasnippet" nil nil)
                       ("bs3navbar:fixed-top" "\n<nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\n	<div class=\"container\">\n		<a class=\"navbar-brand\" href=\"${1:#}\">${2:Title}</a>\n		<ul class=\"nav navbar-nav\">\n			<li class=\"active\">\n				<a href=\"#\">${3:Home}</a>\n			</li>\n			<li>\n				<a href=\"#\">${4:Link}</a>\n			</li>\n		</ul>\n	</div>\n</nav>\n" "bs3navbar:fixed-top" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-fixed-top.yasnippet" nil nil)
                       ("bs3navbar:fixed-bottom" "\n<nav class=\"navbar navbar-default navbar-fixed-bottom\" role=\"navigation\">\n	<div class=\"container\">\n		<a class=\"navbar-brand\" href=\"${1:#}\">${2:Title}</a>\n		<ul class=\"nav navbar-nav\">\n			<li class=\"active\">\n				<a href=\"#\">${3:Home}</a>\n			</li>\n			<li>\n				<a href=\"#\">${4:Link}</a>\n			</li>\n		</ul>\n	</div>\n</nav>\n" "bs3navbar:fixed-bottom" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-fixed-bottom.yasnippet" nil nil)
                       ("bs3navbar:brand" "\n<a class=\"navbar-brand\" href=\"${1:/}\">${2:Title}</a>\n" "bs3navbar:brand" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-brand.yasnippet" nil nil)
                       ("bs3navbar:basic" "\n<div class=\"navbar\">\n	<div class=\"container-fluid\">\n		<a class=\"navbar-brand\" href=\"#\">${1:Title}</a>\n		<ul class=\"nav navbar-nav\">\n			<li class=\"active\">\n				<a href=\"#\">${2:Home}</a>\n			</li>\n			<li>\n				<a href=\"#\">${3:Link}</a>\n			</li>\n		</ul>\n	</div>\n</div>\n" "bs3navbar:basic" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/navigation/bs3navbar-basic.yasnippet" nil nil)))


;;; Do not edit! File generated at Thu Jun 23 21:49:31 2016
