;;; Compiled snippets and support files for `ruby-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'ruby-mode
                     '(("xput" "xhr :put, :${1:update}, id: ${2:1}, ${3:object}: { $4 }$0" "xput" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/xhr-put.yasnippet" nil nil)
                       ("xpost" "xhr :post, :${1:create}, ${2:object}: { $3 }" "xpost" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/xhr-post.yasnippet" nil nil)
                       ("xget" "xhr :get, :${1:show}${2:, id: ${3:1}}$0" "xget" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/xhr-get.yasnippet" nil nil)
                       ("xdelete" "xhr :delete, :${1:destroy}, id: ${2:1}$0" "xdelete" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/xhr-delete.yasnippet" nil nil)
                       ("format" "format.${1:js|xml|html}${2: { $0 \\}}" "format" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/wants_format.yasnippet" nil nil)
                       ("verify" "verify only: [:$1], method: :post, render: { status: 500, text: \"use HTTP-POST\" }\n" "verify" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/verify-(verify).yasnippet" nil nil)
                       ("vuif" "validates_uniqueness_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:must be unique}\", if: proc { |obj| ${6:obj.condition?} }}" "vuif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_uniqueness_of-if-(vuif).yasnippet" nil nil)
                       ("vu" "validates_uniqueness_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:must be unique}\"}" "vu" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_uniqueness_of-(vu).yasnippet" nil nil)
                       ("vpif" "validates_presence_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:can't be blank}\"}, if: proc { |obj| ${5:obj.condition?} }}" "vpif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_presence_of-if-(vpif)-2.yasnippet" nil nil)
                       ("vp" "validates_presence_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:can't be blank}\"}" "vp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_presence_of-(vp).yasnippet" nil nil)
                       ("vn" "validates_numericality_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:is not a number}\"}" "vn" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_numericality_of.yasnippet" nil nil)
                       ("vnif" "validates_numericality_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:is not a number}\"}, if: proc { |obj| ${5:obj.condition?} }}" "vnif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_numericality_of-if.yasnippet" nil nil)
                       ("vlif" "validates_length_of :${1:attribute}, within: ${2:3..20}${3:, on: :${4:create}, message: \"${5:must be present}\"}, if: proc { |obj| ${6:obj.condition?} }}" "vlif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_length_of-if.yasnippet" nil nil)
                       ("vl" "validates_length_of :${1:attribute}, within: ${2:3..20}${3:, on: :${4:create}, message: \"${5:must be present}\"}" "vl" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_length_of-(vl).yasnippet" nil nil)
                       ("vi" "validates_inclusion_of :${1:attribute}${2:, in: ${3:%w( ${4:mov avi} )}, on: :${5:create}, message: \"${6:extension %s is not included in the list}\"}" "vi" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_inclusion_of.yasnippet" nil nil)
                       ("viif" "validates_inclusion_of :${1:attribute}${2:, in: ${3:%w( ${4:mov avi} )}, on: :${5:create}, message: \"${6:extension %s is not included in the list}\"}, if: proc { |obj| ${7:obj.condition?} }}" "viif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_inclusion_of-if.yasnippet" nil nil)
                       ("vf" "validates_format_of :${1:attribute}, with: /${2:^[${3:\\w\\d}]+\\$}/${4:, on: :${5:create}, message: \"${6:is invalid}\"}" "vf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_format_of.yasnippet" nil nil)
                       ("vfif" "validates_format_of :${1:attribute}, with: /${2:^[${3:\\w\\d}]+\\$}/${4:, on: :${5:create}, message: \"${6:is invalid}\"}, if: proc { |obj| ${7:obj.condition?} }}" "vfif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_format_of-if.yasnippet" nil nil)
                       ("veif" "validates_exclusion_of :${1:attribute}${2:, in: ${3:%w( ${4:mov avi} )}, on: :${5:create}, message: \"${6:extension %s is not allowed}\"}, if: proc { |obj| ${7:obj.condition?} }}" "veif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_exclusion_of-if-(veif).yasnippet" nil nil)
                       ("ve" "validates_exclusion_of :${1:attribute}${2:, in: ${3:%w( ${4:mov avi} )}, on: :${5:create}, message: \"${6:extension %s is not allowed}\"}" "ve" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_exclusion_of-(ve).yasnippet" nil nil)
                       ("vcif" "validates_confirmation_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:should match confirmation}\", if: proc { |obj| ${5:obj.condition?} }}" "vcif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_confirmation_of-if-(vcif).yasnippet" nil nil)
                       ("vc" "validates_confirmation_of :${1:attribute}${2:, on: :${3:create}, message: \"${4:should match confirmation}\"}" "vc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_confirmation_of-(vc).yasnippet" nil nil)
                       ("vaif" "validates_associated :${1:attribute}${2:, on: :${3:create}, if: proc { |obj| ${5:obj.condition?} }}" "vaif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_associated-if-(vaif).yasnippet" nil nil)
                       ("va" "validates_associated :${1:attribute}${2:, on: :${3:create}}" "va" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_associated-(va).yasnippet" nil nil)
                       ("vao" "validates_acceptance_of :${1:terms}${2:${3:, accept: \"${4:1}\"}${5:, message: \"${6:You must accept the terms of service}\"}}" "vao" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_acceptance_of.yasnippet" nil nil)
                       ("vaoif" "validates_acceptance_of :${1:terms}${2:${3:, accept: \"${4:1}\"}${5:, message: \"${6:You must accept the terms of service}\"}}, if: proc { |obj| ${7:obj.condition?} }}" "vaoif" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/validates_acceptance_of-if.yasnippet" nil nil)
                       ("t." "t.timestamps\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_timestamps-(tctss).yasnippet" nil nil)
                       ("t." "t.timestamp :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_timestamp-(tcts).yasnippet" nil nil)
                       ("t." "t.time :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_time-(tcti).yasnippet" nil nil)
                       ("t." "t.text :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_text-(tct).yasnippet" nil nil)
                       ("t." "t.string :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_string-(tcs).yasnippet" nil nil)
                       ("t." "t.rename(:${1:old_column_name}, :${2:new_column_name})\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_rename-(tre).yasnippet" nil nil)
                       ("t." "t.references :${1:taggable}${2:, polymorphic: ${3:{ default: '${4:Photo}' \\}}}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_references-(tcr).yasnippet" nil nil)
                       ("t." "t.integer :lock_version, null: false, default: 0\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_lock_version-(tcl).yasnippet" nil nil)
                       ("t." "t.integer :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_integer-(tci).yasnippet" nil nil)
                       ("t." "t.float :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_float-(tcf).yasnippet" nil nil)
                       ("t." "t.decimal :${1:title}${2:${3:, precision: ${4:10}}${5:, scale: ${6:2}}}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_decimal-(tcd).yasnippet" nil nil)
                       ("t." "t.datetime :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_datetime-(tcdt).yasnippet" nil nil)
                       ("t." "t.date :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_date-(tcda).yasnippet" nil nil)
                       ("t." "t.boolean :${1:title}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_boolean-(tcb).yasnippet" nil nil)
                       ("t." "t.binary :${1:title}${2:, limit: ${3:2}.megabytes}\nt.$0" "t." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/t_binary-(tcbi).yasnippet" nil nil)
                       ("st" "<%= submit_tag \"${1:Save changes}\"${2:, id: \"${3:submit}\"}${4:, name: \"${5:$3}\"}${6:, class: \"${7:form_$3}\"}${8:, disabled: ${9:false}}${10:, disable_with: \"${11:Please wait...}\"} %>" "st" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/submit_tag.yasnippet" nil nil)
                       ("slt" "<%= stylesheet_link_tag ${1::application}${2:, media: \"${3:all}\"}${4:, cache: ${5:true}} %>" "slt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/stylesheet_link_tag-(slt).yasnippet" nil nil)
                       ("scar" "scope :${1:name}, ->(${2:arg}){ where(${3:attribute:} $2) }\n" "scar" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/scope_with_args.yasnippet" nil nil)
                       ("sc" "scope :${1:name}, ->{ where(${2:attr:} ${3:value}) }\n" "sc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/scope.yasnippet" nil nil)
                       ("desc" "describe $1 do\n$2\nend\n" "desc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/rspec-desc.snippet" nil nil)
                       ("resdm" "resources :${1:res_name} do\n  member do\n    ${2:get} :${3:action}\n  end\nend" "resdm" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/routes_resources_member_block.yasnippet" nil nil)
                       ("resdc" "resources :${1:res_name} do\n  collection do\n    ${2:get} :${3:action}\n  end\nend" "resdc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/routes_resources_collection_block.yasnippet" nil nil)
                       ("resd" "resources :${1:res_name} do\n  $2\nend" "resd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/routes_resources_block.yasnippet" nil nil)
                       ("res" "resources :${1:res_name}" "res" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/routes_resources.yasnippet" nil nil)
                       ("reso" "resources :${1:res_name}, only: [:${2:index}]" "reso" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/routes_resource_only.yasnippet" nil nil)
                       ("returning" "returning ${1:variable} do${2/(^(?<var>\\s*[a-z_][a-zA-Z0-9_]*\\s*)(,\\g<var>)*,?\\s*$)|.*/(?1: |)/}${2:v}${2/(^(?<var>\\s*[a-z_][a-zA-Z0-9_]*\\s*)(,\\g<var>)*,?\\s*$)|.*/(?1:|)/}\n	$0\nend" "returning" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/returning-do-7Cvariable7C-E280A6-end.yasnippet" nil nil)
                       ("rest" "respond_to do |format|\n	format.${1:html}${2: { $0 \\}}\nend" "rest" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/respond_to.yasnippet" nil nil)
                       ("ru" "render :update do |${2:page}|\n	$2.$0\nend" "ru" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(update).yasnippet" nil nil)
                       ("rts" "render text: \"${1:text to render...}\", status: ${2:401}" "rts" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(text-status)-(rts).yasnippet" nil nil)
                       ("rtlt" "render text: \"${1:text to render...}\", layout: ${2:true}" "rtlt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(text-layout=3Etrue)-(rtlt).yasnippet" nil nil)
                       ("rtl" "render text: \"${1:text to render...}\", layout: \"${2:layoutname}\"" "rtl" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(text-layout)-(rtl).yasnippet" nil nil)
                       ("rt" "render text: \"${1:text to render...}\"" "rt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(text)-(rt).yasnippet" nil nil)
                       ("rps" "render partial: \"${1:item}\", status: ${2:500}" "rps" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(partial-status)-(rps).yasnippet" nil nil)
                       ("rpo" "<%= render partial: \"${1:item}\", object: ${2:@$1} %>" "rpo" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(partial-object)-(rpo).yasnippet" nil nil)
                       ("rpc" "<%= render partial: \"${1:item}\", collection: ${2:@$1s} %>" "rpc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(partial-collection)-(rpc).yasnippet" nil nil)
                       ("rp" "<%= render \"${1:partial/path}\"${2:, ${3:var}: @${3:var}} %>" "rp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(partial)-(rp).yasnippet" nil nil)
                       ("rns" "render nothing: ${1:true}, status: ${2:401}" "rns" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(nothing-status)-(rns).yasnippet" nil nil)
                       ("rn" "render nothing: ${1:true}" "rn" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(nothing)-(rn).yasnippet" nil nil)
                       ("rl" "render layout: \"${1:layoutname}\"" "rl" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(layout)-(rl).yasnippet" nil nil)
                       ("rit" "render inline: \"${1:<%= 'hello' %>}\", type: ${2::rxml}" "rit" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(inline-type)-(rit).yasnippet" nil nil)
                       ("ril" "render inline: \"${1:<%= 'hello' %>}\", locals: { ${2:name}: \"${3:value}\"$4 }" "ril" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(inline-locals)-(ril).yasnippet" nil nil)
                       ("ri" "render inline: \"${1:<%= 'hello' %>}\"" "ri" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(inline)-(ri).yasnippet" nil nil)
                       ("rfu" "render file: \"${1:filepath}\", use_full_path: ${2:false}" "rfu" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(file-use_full_path)-(rfu).yasnippet" nil nil)
                       ("rf" "render file: \"${1:filepath}\"" "rf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(file)-(rf).yasnippet" nil nil)
                       ("ral" "render action: \"${1:action}\", layout: \"${2:layoutname}\"" "ral" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(action-layout)-(ral).yasnippet" nil nil)
                       ("ra" "render action: \"${1:action}\"" "ra" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/render-(action)...-(ra).yasnippet" nil nil)
                       ("repp" "redirect_to(${2:${10:model}s_path})" "repp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/redirect_to-(path-plural).yasnippet" nil nil)
                       ("rep" "redirect_to(${2:${12:model}_path(${13:@}${14:$12})})" "rep" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/redirect_to-(path).yasnippet" nil nil)
                       ("renpp" "redirect_to(${2:${10:parent}_${11:child}_path(${12:@}${13:$10})})" "renpp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/redirect_to-(nested-path-plural).yasnippet" nil nil)
                       ("renp" "redirect_to(${2:${12:parent}_${13:child}_path(${14:@}${15:$12}, ${16:@}${17:$13})})" "renp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/redirect_to-(nested-path).yasnippet" nil nil)
                       ("recai" "redirect_to controller: \"${1:items}\", action: \"${2:show}\", id: ${0:@item}" "recai" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/recai.yasnippet" nil nil)
                       ("reca" "redirect_to controller: \"${1:items}\", action: \"${2:list}\"" "reca" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/reca.yasnippet" nil nil)
                       ("rec" "redirect_to controller: \"${1:items}\"" "rec" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/rec.yasnippet" nil nil)
                       ("reai" "redirect_to action: \"${1:show}\", id: ${0:@item}" "reai" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/reai.yasnippet" nil nil)
                       ("rea" "redirect_to action: \"${1:index}\"" "rea" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/rea.yasnippet" nil nil)
                       ("flash" "flash[:${1:notice}] = \"${2:Successfully created...}\"$0" "flash" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/rails-flash.yasnippet" nil nil)
                       ("lsc" "scope :name, ->(${1:param}){ ${3:['${4:${5:field} = ?}', ${6:$1}]} }\n" "lsc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/named_scope-lambda.yasnippet" nil nil)
                       ("mrw" "mattr_accessor :${0:attr_names}" "mrw" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/mattr_accessor.yasnippet" nil nil)
                       ("mp" "map(&:${1:id})" "mp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/map(-3Asym_proc).yasnippet" nil nil)
                       ("logw" "logger.warn { \"${1:message}\" }$0" "logw" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/logger_warn.yasnippet" nil nil)
                       ("logi" "logger.info { \"${1:message}\" }$0" "logi" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/logger_info.yasnippet" nil nil)
                       ("logf" "logger.fatal { \"${1:message}\" }$0" "logf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/logger_fatal.yasnippet" nil nil)
                       ("loge" "logger.error { \"${1:message}\" }$0" "loge" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/logger_error.yasnippet" nil nil)
                       ("logd" "logger.debug { \"${1:message}\" }$0" "logd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/logger_debug.yasnippet" nil nil)
                       ("lim" "<%= link_to ${1:model}.${2:name}, ${3:${4:$1}_path(${14:$1})} %>" "lim" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/link_to-model.yasnippet" nil nil)
                       ("lipp" "<%= link_to ${1:\"${2:link text...}\"}, ${3:${4:model}s_path} %>" "lipp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/link_to-(path-plural).yasnippet" nil nil)
                       ("lip" "<%= link_to ${1:\"${2:link text...}\"}, ${3:${12:model}_path(${13:@}${14:$12})} %>" "lip" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/link_to-(path).yasnippet" nil nil)
                       ("linpp" "<%= link_to ${1:\"${2:link text...}\"}, ${3:${10:parent}_${11:child}_path(${12:@}${13:$10})} %>" "linpp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/link_to-(nested-path-plural).yasnippet" nil nil)
                       ("linp" "<%= link_to ${1:\"${2:link text...}\"}, ${3:${12:parent}_${13:child}_path(${14:@}${15:$12}, ${16:@}${17:$13})} %>" "linp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/link_to-(nested-path).yasnippet" nil nil)
                       ("licai" "<%= link_to \"${1:link text...}\", controller: \"${2:items}\", action: \"${3:edit}\", id: ${4:@item} %>" "licai" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/licai.yasnippet" nil nil)
                       ("lica" "<%= link_to \"${1:link text...}\", controller: \"${2:items}\", action: \"${3:index}\" %>" "lica" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/lica.yasnippet" nil nil)
                       ("lic" "<%= link_to \"${1:link text...}\", controller: \"${2:items}\" %>" "lic" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/lic.yasnippet" nil nil)
                       ("liai" "<%= link_to \"${1:link text...}\", action: \"${2:edit}\", id: ${3:@item} %>" "liai" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/liai.yasnippet" nil nil)
                       ("lia" "<%= link_to \"${1:link text...}\", action: \"${2:index}\" %>" "lia" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/lia.yasnippet" nil nil)
                       ("jit" "<%= javascript_include_tag ${1::application}${2:, cache: ${3:true}} %>" "jit" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/javascript_include_tag-(jit).yasnippet" nil nil)
                       ("defi" "def initialize(${1:attribute})\n  @$1 = $1\nend" "defi" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/initializer-method.yasnippet" nil nil)
                       ("ist" "<%= image_submit_tag(\"${1:agree.png}\"${2:${3:, id: \"${4:${1/^(\\w+)(\\.\\w*)?$/$1/}}\"}${5:, name: \"${6:${1/^(\\w+)(\\.\\w*)?$/$1/}}\"}${7:, class: \"${8:${1/^(\\w+)(\\.\\w*)?$/$1/}-button}\"}${9:, disabled: ${10:false}}}) %>" "ist" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/image_submit_tag.yasnippet" nil nil)
                       ("hot" "has_one :${1:object}, through: :${2:join_association}${3:, source: :${4:$2_table_foreign_key_to_$1_table}}" "hot" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_one_through-(hot).yasnippet" nil nil)
                       ("ho" "has_one :${1:object}${2:, class_name: \"${3:${1/[[:alpha:]]+|(_)/(?1::\\u$0)/g}}\", foreign_key: \"${4:$1_id}\"}" "ho" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_one-(ho).yasnippet" nil nil)
                       ("hmd" "has_many :${1:object}s${2:, class_name: \"$1\", foreign_key: \"${4:reference}_id\"}, dependent: :destroy$0" "hmd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_many-dependent-=-destroy.yasnippet" nil nil)
                       ("hmt" "has_many :${1:objects}, through: :${2:join_association}${3:, source: :${4:$2_table_foreign_key_to_$1_table}}" "hmt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_many-(through).yasnippet" nil nil)
                       ("hm" "has_many :${1:object}s${2:, class_name: \"$1\", foreign_key: \"${4:reference}_id\"}" "hm" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_many-(hm).yasnippet" nil nil)
                       ("habtm" "has_and_belongs_to_many :${1:object}${2:, join_table: \"${3:table_name}\", foreign_key: \"${4:$1_id}\"}" "habtm" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/has_and_belongs_to_many-(habtm).yasnippet" nil nil)
                       ("ff" "<%= form_for @${1:model} do |f| %>\n  $0\nend" "ff" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for.yasnippet" nil nil)
                       ("ffe" "<%= error_messages_for :${1:model} %>\n\n<% form_for @${2:$1} do |f| -%>\n  $0\nend" "ffe" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-with-errors.yasnippet" nil nil)
                       ("f." "<%= f.text_field :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-text_field.yasnippet" nil nil)
                       ("fftf" "<%= f.text_field :${1:attribute} %>" "fftf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-text_field-2.yasnippet" nil nil)
                       ("f." "<%= f.text_area :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-text_area.yasnippet" nil nil)
                       ("ffta" "<%= f.text_area :${1:attribute} %>" "ffta" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-text_area-2.yasnippet" nil nil)
                       ("f." "<%= f.submit \"${1:Submit}\"${2:, disable_with: '${3:$1ing...}'} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-submit.yasnippet" nil nil)
                       ("ffs" "<%= f.submit \"${1:Submit}\"${2:, disable_with: '${3:$1ing...}'} %>" "ffs" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-submit-2.yasnippet" nil nil)
                       ("f." "<%= f.radio_box :${1:attribute}, :${2:tag_value} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-radio_box.yasnippet" nil nil)
                       ("ffrb" "<%= f.radio_box :${1:attribute}, :${2:tag_value} %>" "ffrb" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-radio_box-2.yasnippet" nil nil)
                       ("f." "<%= f.password_field :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-password_field.yasnippet" nil nil)
                       ("ffpf" "<%= f.password_field :${1:attribute} %>" "ffpf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-password_field-2.yasnippet" nil nil)
                       ("f." "<%= f.label :${1:attribute}${2:, \"${3:${1/[[:alpha:]]+|(_)/(?1: :\\u$0)/g}}\"} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-label.yasnippet" nil nil)
                       ("ffl" "<%= f.label :${1:attribute}${2:, \"${3:${1/[[:alpha:]]+|(_)/(?1: :\\u$0)/g}}\"} %>" "ffl" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-label-2.yasnippet" nil nil)
                       ("f." "<%= f.hidden_field :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-hidden_field.yasnippet" nil nil)
                       ("ffhf" "<%= f.hidden_field :${1:attribute} %>" "ffhf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-hidden_field-2.yasnippet" nil nil)
                       ("f." "<%= f.file_field :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-file_field.yasnippet" nil nil)
                       ("ffff" "<%= f.file_field :${1:attribute} %>" "ffff" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-file_field-2.yasnippet" nil nil)
                       ("f." "<%= f.check_box :${1:attribute} %>" "f." nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-checkbox.yasnippet" nil nil)
                       ("ffcb" "<%= f.check_box :${1:attribute} %>" "ffcb" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/form_for-check_box.yasnippet" nil nil)
                       ("for" "<% if !${1:list}.blank? %>\n  <% for ${2:item} in $1 %>\n    $3\n  <% end %>\n<% else %>\n  $4\n<% end %>\n" "for" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/for-loop-erb.yasnippet" nil nil)
                       ("fp" "find(params[:${1:id}])" "fp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/find_params_id_(fp).yasnippet" nil nil)
                       ("fini" "find(${1:id})" "fini" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/find(id).yasnippet" nil nil)
                       ("end" "<% end %>" "end" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/end.yasnippet" nil nil)
                       ("deftp" "def test_should_post_${1:action}\n	${3:@$2 = ${4:$2s}(:${5:fixture_name})\n	}post :$1${6:, id: @$2.to_param}, ${2:model}: { $0 }\n	assert_response :redirect\n\nend" "deftp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/def-post-request.yasnippet" nil nil)
                       ("deftg" "def test_should_get_${1:action}\n	${2:@${3:model} = ${4:$3s}(:${5:fixture_name})\n	}get :$1${6:, id: @$3.to_param}\n	assert_response :success\n	$0\nend" "deftg" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/def-get-request.yasnippet" nil nil)
                       ("desc" "describe $1 do\n$2\nend" "desc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/def-create-resource.yasnippet" nil nil)
                       ("crud" "\n  def index\n    @$1 = ${1/(.+)/\\u$1/g}.scoped\n  end\n\n  def show\n    @$1 = ${1/(.+)/\\u$1/g}.find(params[:id])\n  end\n\n  def create\n    @$1 = ${1/(.+)/\\u$1/g}.new(params[:$1])\n  end\n\n  def update\n    @$1 = ${1/(.+)/\\u$1/g}.find(params[:id])\n  end\n\n  def edit\n    @$1 = ${1/(.+)/\\u$1/g}.find(params[:id])\n  end\n\n  def destroy\n    $1 = ${1/(.+)/\\u$1/g}.find(params[:id])\n  end" "crud" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/crud-actions.yasnippet" nil nil)
                       ("class" "class ${1:${TM_FILENAME/(?:\\A|_)([A-Za-z0-9]+)(?:\\.rb)?/(?2::\\u$1)/g}}\n$0\nend" "class" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/class-end.yasnippet" nil nil)
                       ("crw" "cattr_accessor :${0:attr_names}" "crw" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/cattr_accessor.yasnippet" nil nil)
                       ("bb" "\nbyebug\n" "bb" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/byebug.yasnippet" nil nil)
                       ("bp" "\nbinding.pry\n" "bp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/binding_pry.yasnippet" nil nil)
                       ("bt" "belongs_to :${1:object}${2:, class_name: \"${3:${1/[[:alpha:]]+|(_)/(?1::\\u$0)/g}}\", foreign_key: \"${4:$1_id}\"}" "bt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/belongs_to-(bt).yasnippet" nil nil)
                       ("befvou" "before_validation ${1:validation_method}, on: :update" "befvou" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_validation_on_update.yasnippet" nil nil)
                       ("befvoc" "before_validation ${1:validation_method}, on: :create" "befvoc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_validation_on_create.yasnippet" nil nil)
                       ("befv" "before_validation " "befv" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_validation.yasnippet" nil nil)
                       ("befu" "before_update " "befu" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_update.yasnippet" nil nil)
                       ("befs" "before_save " "befs" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_save.yasnippet" nil nil)
                       ("befd" "before_destroy " "befd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_destroy.yasnippet" nil nil)
                       ("befc" "before_create " "befc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/before_create.yasnippet" nil nil)
                       ("ass" "assert_select '${1:path}'${2:, ${3:text}: ${4:'${5:inner_html}'}}${6: do\n	$0\nend}" "ass" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_select.yasnippet" nil nil)
                       ("artpp" "assert_redirected_to ${10:${2:model}s_path}" "artpp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_redirected_to-(path-plural).yasnippet" nil nil)
                       ("artp" "assert_redirected_to ${2:${12:model}_path(${13:@}${14:$12})}" "artp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_redirected_to-(path).yasnippet" nil nil)
                       ("artnpp" "assert_redirected_to ${10:${2:parent}_${3:child}_path(${4:@}${5:$2})}" "artnpp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_redirected_to-(nested-path-plural).yasnippet" nil nil)
                       ("artnp" "assert_redirected_to ${2:${12:parent}_${13:child}_path(${14:@}${15:$12}, ${16:@}${17:$13})}" "artnp" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_redirected_to-(nested-path).yasnippet" nil nil)
                       ("asnd" "assert_no_difference \"${1:Model}.${2:count}\" do\n  $0\nend" "asnd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_no_difference.yasnippet" nil nil)
                       ("asd" "assert_difference \"${1:Model}.${2:count}\", ${3:1} do\n  $0\nend" "asd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert_difference.yasnippet" nil nil)
                       ("asg" "assert(${1:var} = assigns(:$1), \"Cannot find @$1\")\n$0" "asg" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/assert(var-=-assigns(3Avar)).yasnippet" nil nil)
                       ("aftvou" "after_validation ${1:validation_method}, on: :update" "aftvou" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_validation_on_update.yasnippet" nil nil)
                       ("aftvoc" "after_validation ${1:validation_method}, on: :create" "aftvoc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_validation_on_create.yasnippet" nil nil)
                       ("aftv" "after_validation " "aftv" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_validation.yasnippet" nil nil)
                       ("aftu" "after_update " "aftu" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_update.yasnippet" nil nil)
                       ("afts" "after_save " "afts" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_save.yasnippet" nil nil)
                       ("aftd" "after_destroy " "aftd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_destroy.yasnippet" nil nil)
                       ("aftc" "after_create " "aftc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/after_create.yasnippet" nil nil)
                       ("arc" "class ${1:${TM_FILENAME/(?:\\A|_)([A-Za-z0-9]+)(?:\\.rb)?/(?2::\\u$1)/g}} < ActiveRecord::Base\n$0\nend" "arc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/active-record-class-end.yasnippet" nil nil)
                       ("anaf" "accepts_nested_attributes_for :${1:relationship}, ${2:reject_if: ->(attributes){ attributes['name'].blank? \\}}${3:, allow_destroy: true}" "anaf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/accepts_nested_attributes_for.yasnippet" nil nil)
                       ("asre" "assert_response :${1:success}, @response.body$0" "asre" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Test-Assert-Response-(are).yasnippet" nil nil)
                       ("art" "assert_redirected_to ${2:action: \"${1:index}\"}" "art" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Test-Assert-Redirected-To-(art).yasnippet" nil nil)
                       ("tre" "t.rename(:${1:old_column_name}, :${2:new_column_name})\n$0" "tre" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Table-column(s)-rename.yasnippet" nil nil)
                       ("rdb" "RAILS_DEFAULT_LOGGER.debug \"${1:message}\"$0" "rdb" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/RAILS_DEFAULT_LOGGER.debug-(rdb).yasnippet" nil nil)
                       ("mcol" "rename_column :${1:table}, :${2:old_column_name}, :${3:new_column_name}" "mcol" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Rename-Column.yasnippet" nil nil)
                       ("mind" "remove_index :${1:table}, name: :${2:index_name}" "mind" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Remove-Index.yasnippet" nil nil)
                       ("mcol" "remove_column :${1:table}, :${2:column}" "mcol" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Remove-Column.yasnippet" nil nil)
                       ("mtab" "drop_table :${1:table}" "mtab" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Drop-Table-(mdct).yasnippet" nil nil)
                       ("mtab" "create_table :${1:table} do |t|\n  t.${2:string} :${3:name}\n\n  t.timestamps\nend\n" "mtab" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Create-Table-(mdct).yasnippet" nil nil)
                       ("mccc" "t.column ${1:title}, :${2:string}\nmccc$0" "mccc" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Create-Column-Continue-(mccc).yasnippet" nil nil)
                       ("mcol" "t.column ${1:title}, :${2:string}\n$0" "mcol" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Create-Column-(mcc).yasnippet" nil nil)
                       ("mcol" "change_column :${1:table}, :${2:column}, :${3:string}${4:, ${5:limit}: ${6:255}}" "mcol" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Change-Column.yasnippet" nil nil)
                       ("mind" "add_index :${1:table}, :${2:columns}${4:, ${5:name}: \"${6:custom_index_name}\"}" "mind" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Add-Index.yasnippet" nil nil)
                       ("mcol" "add_column :${1:table}, :${2:column}, :${3:string}${4:, ${5:limit}: ${6:255}}" "mcol" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Migration-Add-Column.yasnippet" nil nil)
                       ("$L" "\\$LABEL" "$L" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/LABEL.yasnippet" nil nil)
                       ("tctss" "t.timestamps\n$0" "tctss" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-timestamps-columns.yasnippet" nil nil)
                       ("tcts" "t.timestamp :${1:title}\n$0" "tcts" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-timestamp-column.yasnippet" nil nil)
                       ("tcti" "t.time :${1:title}\n$0" "tcti" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-time-column.yasnippet" nil nil)
                       ("tct" "t.text :${1:title}\n$0" "tct" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-text-column.yasnippet" nil nil)
                       ("tcs" "t.string :${1:title}\n$0" "tcs" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-string-column.yasnippet" nil nil)
                       ("tcr" "t.references :${1:taggable}${2:, polymorphic: ${3:{ default: '${4:Photo}' \\}}}\n$0" "tcr" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-references-column.yasnippet" nil nil)
                       ("tcl" "t.integer :lock_version, null: false, default: 0\n$0" "tcl" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-lock_version-column.yasnippet" nil nil)
                       ("tci" "t.integer :${1:title}\n$0" "tci" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-integer-column.yasnippet" nil nil)
                       ("cla" "require File.dirname(__FILE__) + '/../test_helper'\n\nclass ${1:Model}ControllerTest < ActionController::TestCase\n	deft$0\nend\n" "cla" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-functional-test-class.yasnippet" nil nil)
                       ("tcf" "t.float :${1:title}\n$0" "tcf" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-float-column.yasnippet" nil nil)
                       ("tcd" "t.decimal :${1:title}${2:${3:, precision: ${4:10}}${5:, scale: ${6:2}}}\n$0" "tcd" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-decimal-column.yasnippet" nil nil)
                       ("tcdt" "t.datetime :${1:title}\n$0" "tcdt" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-datetime-column.yasnippet" nil nil)
                       ("tcda" "t.date :${1:title}\n$0" "tcda" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-date-column.yasnippet" nil nil)
                       ("con" "class ${1:${TM_FILENAME/(?:\\A|_)([A-Za-z0-9]+)(?:\\.rb)?/(?2::\\u$1)/g}} < ${2:Application}Controller\n  $3\nend" "con" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-controller-class.yasnippet" nil nil)
                       ("tcb" "t.boolean :${1:title}\n$0" "tcb" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-boolean-column.yasnippet" nil nil)
                       ("tcbi" "t.binary :${1:title}${2:, limit: ${3:2}.megabytes}\n$0" "tcbi" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/Create-binary-column.yasnippet" nil nil)
                       ("fi" "<%= Fixtures.identify(:${1:name}) %>$0" "fi" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/3C=-Fixtures_identify(3Asymbol)-3E.yasnippet" nil nil)
                       ("ft" "<%= form_tag(${1:action: \"${5:update}\"}${6:, {:${8:class}: \"${9:form}\"\\}}) do %>\n  $0\nend" "ft" nil nil nil "/Users/ok/.spacemacs.d/snippets/ruby-mode/180-rails-form_tag.yasnippet" nil nil)))


;;; Do not edit! File generated at Tue Aug 30 16:45:06 2016
