;;; Compiled snippets and support files for `panels'
;;; Snippet definitions:
;;;
(yas-define-snippets 'panels
                     '(("bs3panel" "\n<div class=\"panel panel-${1:default}\">\n	<div class=\"panel-body\">\n		${2:Basic panel example}\n	</div>\n</div>\n" "bs3panel" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel.yasnippet" nil nil)
                       ("bs3panel:warning" "\n<div class=\"panel panel-${1:warning}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:warning" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-warning.yasnippet" nil nil)
                       ("bs3panel:table" "\n<div class=\"panel panel-${1:default}\">\n	<!-- Default panel contents -->\n	<div class=\"panel-heading\">Panel heading</div>\n	<div class=\"panel-body\">\n		<p>Text goes here...</p>\n	</div>\n\n	<!-- Table -->\n	<table class=\"table\">\n		<thead>\n			<tr>\n				<th>${2:Heading 1}</th>\n			</tr>\n			<tr>\n				<th>${3:Heading 2}</th>\n			</tr>\n		</thead>\n		<tbody>\n			<tr>\n				<td>${4:Content 1}</td>\n			</tr>\n			<tr>\n				<td>${5:Content 2}</td>\n			</tr>\n		</tbody>\n	</table>\n</div>\n" "bs3panel:table" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-table.yasnippet" nil nil)
                       ("bs3panel:success" "\n<div class=\"panel panel-${1:success}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:success" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-success.yasnippet" nil nil)
                       ("bs3panel:primary" "\n<div class=\"panel panel-${1:primary}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:primary" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-primary.yasnippet" nil nil)
                       ("bs3panel:info" "\n<div class=\"panel panel-${1:info}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:info" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-info.yasnippet" nil nil)
                       ("bs3panel:heading" "\n<div class=\"panel panel-${1:default}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:heading" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-heading.yasnippet" nil nil)
                       ("bs3panel:footer" "\n<div class=\"panel panel-default\">\n	<div class=\"panel-body\">\n		${1:Panel content}\n	</div>\n	<div class=\"panel-footer\">\n		${2:Panel footer}\n	</div>\n</div>\n" "bs3panel:footer" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-footer.yasnippet" nil nil)
                       ("bs3panel:danger" "\n<div class=\"panel panel-${1:danger}\">\n	<div class=\"panel-heading\">\n		<h3 class=\"panel-title\">Panel title</h3>\n	</div>\n	<div class=\"panel-body\">\n		${2:Panel content}\n	</div>\n</div>\n" "bs3panel:danger" nil nil nil "/Users/ok/.spacemacs.d/snippets/web-mode/panels/bs3panel-danger.yasnippet" nil nil)))


;;; Do not edit! File generated at Thu Jun 23 21:49:31 2016
